import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // 💡 背景画像用のスタイル
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  // 💡 SafeAreaView 用のスタイル
  safeArea: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  logoContainer: {
    width: '100%',
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 25,
    zIndex: 10,
  },
  logoImage: {
    width: 440,
    height: 220,
  },
  card: {
    width: '100%',
    backgroundColor: 'rgba(255, 255, 240, 0.95)',
    borderRadius: 36,
    paddingHorizontal: 28,
    paddingTop: 32,
    paddingBottom: 40,
    borderWidth: 5,
    borderColor: '#FFD600',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  title: {
    fontSize: 24,
    fontWeight: '900',
    color: '#3D2817',
    textAlign: 'center',
    marginBottom: 24,
  },
  inputGroup: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#3D2817',
    marginBottom: 6,
  },
  input: {
    backgroundColor: '#FFF',
    borderWidth: 2.5,
    borderColor: '#4E3117',
    borderRadius: 14,
    height: 48,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#3D2817',
  },
  forgotBtn: {
    alignSelf: 'flex-end',
    marginTop: 4,
    marginBottom: 24,
  },
  forgotText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#3D2817',
  },
  messageText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#3D2817',
    textAlign: 'center',
    lineHeight: 24,
    marginVertical: 16,
  },
  buttonContainer: {
    gap: 12,
    alignItems: 'center',
    width: '100%',
  },
  primaryBtn: {
    backgroundColor: '#3B97FF',
    width: 200,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
  },
  primaryBtnText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '900',
  },
  secondaryBtn: {
    backgroundColor: '#FFF',
    borderWidth: 2.5,
    borderColor: '#3B97FF',
    width: 200,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondaryBtnText: {
    color: '#3B97FF',
    fontSize: 16,
    fontWeight: '900',
  },
});